### ISSUE TITLE
domain lua not yet registered

### ISSUE THREAD

**Issue by robspsj** [boolangery/sphinx-lua#2]
i follower sphinx getting started and was able to generate a simple html documentation, but when i add   sphinx_lua as my only extension i am no longer able to compile my project, i get this message: 
```
Running Sphinx v1.8.4

Extension error:
domain lua not yet registered
make: *** [html] Error 2
```

**Comment by boolangery** [comment]
Hi, 
I updated the readme, you need to include sphinxcontrib.luadomain extension too:

```python
extensions = ['sphinx_lua', 'sphinxcontrib.luadomain']
```

**Comment by robspsj** [comment]
thank you, it works now :D

**Comment by Azzeccagarbugli** [comment]
I have the same issue actually even if I followed the updated procedure
