### ISSUE TITLE
Domain Lua not registered 

### ISSUE THREAD

**Issue by Azzeccagarbugli** [boolangery/sphinx-lua#5]
Hi, 

I'm trying to use this plugin for my project's documentation but when I try to run the command `make html`, this is the result:

```
Running Sphinx v3.0.3

Extension error:
domain lua not yet registered
make: *** [Makefile:20: html] Errore 2
```

I configured the `conf.py` as you suggested in the README but still I got this issue.

Thanks in advance!

**Comment by boolangery** [comment]
Hi,
Can you try to put 'sphinxcontrib.luadomain' before 'sphinx_lua' in your conf file ? (if its not the case)

**Comment by boolangery** [comment]
If not working, try to pull sphinx-luadomain 1.1.2

**Comment by Azzeccagarbugli** [comment]
> Hi,
> Can you try to put 'sphinxcontrib.luadomain' before 'sphinx_lua' in your conf file ? (if its not the case)

This didn't work

> If not working, try to pull sphinx-luadomain 1.1.2

What do you mean? The version is still the 1.1.1, I guess that I should wait for the update

**Comment by Azzeccagarbugli** [comment]
I even tried to do a clean installation of everything, but nothing changed unfortunately

**Comment by Azzeccagarbugli** [comment]
Pinging you, it's quite urgent

**Comment by boolangery** [comment]
Sorry, there is a 1.1.2 check here: https://github.com/boolangery/sphinx-luadomain

Just try to install it inside your python env: `pip install sphinxcontrib-luadomain==1.1.2`

**Comment by Azzeccagarbugli** [comment]
> Sorry, there is a 1.1.2 check here: https://github.com/boolangery/sphinx-luadomain
> 
> Just try to install it inside your python env: `pip install sphinxcontrib-luadomain==1.1.2`

```
ERROR: Could not find a version that satisfies the requirement sphinxcontrib-luadomain==1.1.2 (from versions: 1.0, 1.0.1, 1.1.0, 1.1.1)
ERROR: No matching distribution found for sphinxcontrib-luadomain==1.1.2
```

Seems that is still not present

**Comment by boolangery** [comment]
My bad, just forgotten to push the package to pypi, please try again

**Comment by Azzeccagarbugli** [comment]
Perfect, now all is working properly! Thank you!
