### ISSUE TITLE
Disable `:private-members:`?

### ISSUE THREAD

**Issue by FreeMasen** [boolangery/sphinx-lua#8]
I am curious if it is possible to configure this extension to not render `autoclass` members with a leading `_` or marked with the `private` attribute?

**Comment by boolangery** [comment]
It seems to already be the case no ? Just tested with:
```
--- @param bar number
function cls:_privateMember(bar)
end
```
And its not rendered

**Comment by FreeMasen** [comment]
Sorry, I should have provided some more context for this issue. I am seeing that this is rendering all items prefixed with an `_` or marked as `@field private`. 

[Here is an example repository](https://github.com/FreeMasen/lua-doc-min-private), which renders [these docs](https://freemasen.github.io/lua-doc-min-private/). 

- [Here is the action config](https://github.com/FreeMasen/lua-doc-min-private/blob/f0073a4c2d04524451150f9060e3e9e686bd6020/.github/workflows/generate-docs.yaml)
- [Here is the sphinx config](https://github.com/FreeMasen/lua-doc-min-private/blob/f0073a4c2d04524451150f9060e3e9e686bd6020/doc-src/conf.py)
- [Here is the luadoc config](https://github.com/FreeMasen/lua-doc-min-private/blob/f0073a4c2d04524451150f9060e3e9e686bd6020/luadoc.json)

Is there some configuration I am missing?

**Comment by boolangery** [comment]
Ok thanks for the clarification, it should be fixed in 1.1.5 and :private-members: should work as expected !
